services:
    api:
      build: .
      container_name: restarauntAPI
      ports:
        - 8080:8080

    db:
      ports:
        - 5432:5432
      container_name: postgresDB
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: postgres